server:
  port: 8080

spring:
  sql:
    init:
      mode: ALWAYS
  application:
    name: DistributedScheduling
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: false
  datasource:
    url: jdbc:mysql://localhost:3306/distributedScheduling?createIfNotExists=true
    username: root
    password: 12345678
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

logging:
  level:
    root: INFO