server:
  port: 8080

spring:
  sql:
    init:
      mode: EMBEDDED
  application:
    name: DistributedScheduling
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
  datasource:
    url: jdbc:h2:mem:distributedScheduling?createDatabaseIfNotExist=true
    username: sa
    password:
  h2:
    console:
      enabled: true
logging:
  level:
    root: INFO