server:
  port: 8080

spring:
  sql:
    init:
      mode: ALWAYS
  application:
    name: DistributedScheduling
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
  config:
    import: optional:secret.properties
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        format_sql: false
        show_sql: false

  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST}:3306/distributed_scheduling?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

logging:
  level:
    root: INFO